### ISSUE TITLE
TrieProcessor don't allow rule duplicates

### ISSUE THREAD

**Issue by pandemorra** [RGafiyatullin/la-rete#2]
```
case class TestData(a: Long, b: String)
object AProp extends Property[TestData, Long] {
      override def apply(in: TestData): Long = in.a
      override def isDefinedAt(obj: Any): Boolean = obj.isInstanceOf[TestData]
}
def aIs(v: Long): Filter[TestData, TestData] = Filter.property(AProp, v).as[TestData]

TrieProcessor.createProcessor(Seq(
      aIs(42) -> true,
      aIs(42) -> false
))
```

throws:

> assertion failed
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:204)
	at com.github.rgafiyatullin.la_rete.processors.trie.IntoTrie.buildTrie(IntoTrie.scala:57)
	at com.github.rgafiyatullin.la_rete.processors.trie.IntoTrie.$anonfun$buildTrie$6(IntoTrie.scala:76)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:125)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.github.rgafiyatullin.la_rete.processors.trie.IntoTrie.buildTrie(IntoTrie.scala:74)
	at com.github.rgafiyatullin.la_rete.processors.trie.IntoTrie.apply(IntoTrie.scala:88)
	at com.github.rgafiyatullin.la_rete.processors.trie.TrieProcessor.<init>(TrieProcessor.scala:42)
	at com.github.rgafiyatullin.la_rete.processors.trie.TrieProcessor$.createProcessor(TrieProcessor.scala:9)

**Comment by RGafiyatullin** [comment]
#3
